--EXPLORATORY DATA ANALYSIS

----------------------------------------
--DATABASE EXPLORATION
--Explore All Objects in the Database

SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore All Columns in the Database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE 'dim_customers'

----------------------------------------

--DIMENSIONS EXPLORATION: Identifying unique values (or categories) in each dimension. 
--This helps to recognize how data might be grouped or segmented which is useful for later analysis.

SELECT DISTINCT country FROM gold.dim_Customers

SELECT DISTINCT category, subcategory, product_name FROM gold.dim_Products
ORDER BY 1,2,3

------------------------------------------

--DATE EXPLORATION: Identify the earliest and latest dates (boundaries) to understand the scope of date and timespan.

SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(MONTH, MIN(order_date), MAX(order_date) ) AS order_range
FROM gold.fact_Sales

SELECT 
	MIN(birth_date) AS oldest_customer,
	DATEDIFF(YEAR, MIN(birth_date), GETDATE() ) AS oldest_age,
	MAX(birth_date) AS  youngest_customer,
	DATEDIFF(YEAR, MAX(birth_date), GETDATE() ) AS youngest_age
FROM gold.dim_customers

-----------------------------------------


--MEASURES EXPLORATION
--Calculate the key metric of business 
--Highest Level of Aggregation | Lowest Level of Details

--Find Total Sales
SELECT SUM (sales_amount) AS total_sales FROM gold.fact_Sales 

--Find how many items are sold
SELECT SUM (quantity) AS total_quantity FROM gold.fact_Sales

--Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_Sales

--Find the total number of orders
SELECT COUNT (order_number) AS total_orders FROM gold.fact_Sales
SELECT COUNT (DISTINCT order_number) AS total_orders FROM gold.fact_Sales -- Find unique orders

--Find total number of Products
SELECT COUNT (product_key) AS total_products FROM gold.dim_Products

--Find total number of Customers
SELECT COUNT (customer_key) AS total_customers FROM gold.dim_Customers

--Find total number of Customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS toal_customers FROM gold.fact_Sales

--Generate a report that shows all key metrics of business
SELECT 'Total Sales' AS measure_name, SUM (sales_amount) AS measure_value FROM gold.fact_Sales
UNION ALL
SELECT 'Total Quantity', SUM (quantity) FROM gold.fact_Sales
UNION ALL
SELECT 'Average Selling Price', AVG(price) FROM gold.fact_Sales
UNION ALL
SELECT 'Total Number of Orders', COUNT (DISTINCT order_number) FROM gold.fact_Sales
UNION ALL
SELECT 'Total Number of Products', COUNT (product_key)  FROM gold.dim_Products
UNION ALL
SELECT 'Total Number of Customers', COUNT (customer_key) FROM gold.dim_Customers
UNION ALL
SELECT 'Total Number of Customers who placed an order', COUNT(DISTINCT customer_key) FROM gold.fact_Sales

--------------------------------------------------

--MAGNITUDE
--Compare the measure values by categories. It helps us understand the importance of different categories

--Find total numbers of customers by countries
SELECT
	country,
	COUNT (customer_key) as total_customers
FROM gold.dim_Customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender
SELECT
	gender,
	COUNT (customer_key) AS total_customers
FROM gold.dim_Customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category
SELECT
	category,
	COUNT (product_key) AS total_products
FROM gold.dim_Products
GROUP BY category
ORDER BY total_products DESC

--Average cost in each category
SELECT
	category,
	AVG (product_cost) AS average_cost
FROM gold.dim_Products
GROUP BY category
ORDER BY average_cost DESC

--Total revenue generated for each category
SELECT
	p.category,
	SUM (s.sales_amount) AS revenue
FROM gold.fact_Sales s
LEFT JOIN gold.dim_Products p
	ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY revenue DESC

--Total revenue generated by each customer
SELECT 
	c.customer_number,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS revenue
FROM gold.fact_Sales s
LEFT JOIN gold.dim_Customers c
	ON s.customer_key = c.customer_key
GROUP BY c.customer_number,
	c.first_name,
	c.last_name
ORDER BY revenue DESC

--Distribution of sold items across countries
SELECT
	c.country,
	SUM (s.quantity) AS quantity
FROM gold.fact_Sales s
LEFT JOIN gold.dim_Customers c
	ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY quantity DESC

------------------------------------------

--RANKING: Orders the values of dimensions by measures

--5 products that generated highest revenue
SELECT TOP 5
	p.product_name,
	SUM (s.sales_amount) AS total_revenue
FROM gold.fact_Sales s
LEFT JOIN gold.dim_Products p
	ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

--The above query can also be written using windows function which provides more flexibility
SELECT * 
FROM (
	SELECT
		p.product_name,
		SUM (s.sales_amount) AS total_revenue,
		ROW_NUMBER() OVER (ORDER BY SUM (s.sales_amount) DESC) AS rank_prd
	FROM gold.fact_Sales s
	LEFT JOIN gold.dim_Products p
		ON p.product_key = s.product_key
	GROUP BY p.product_name
)t
WHERE rank_prd <=5

--5 worst performing products in terms of sales
SELECT TOP 5
	p.product_name,
	SUM (s.sales_amount) AS total_revenue
FROM gold.fact_Sales s
LEFT JOIN gold.dim_Products p
	ON p.product_key = s.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

-- TOP 10 customers who generated highest revenues
SELECT TOP 10
c.customer_number,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS revenue
FROM gold.fact_Sales s
LEFT JOIN gold.dim_Customers c
	ON s.customer_key = c.customer_key
GROUP BY c.customer_number,
	c.first_name,
	c.last_name
ORDER BY revenue DESC

--TOP 3 customers who has lowest orders
SELECT TOP 3
c.customer_number,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT s.order_number) AS orders
FROM gold.fact_Sales s
LEFT JOIN gold.dim_Customers c
	ON s.customer_key = c.customer_key
GROUP BY c.customer_number,
	c.first_name,
	c.last_name
ORDER BY orders 